sudo: false
language: python
python:
- '2.7'
env:
- TOX_ENV=flake8
- TOX_ENV=py26
- TOX_ENV=py27
install:
- pip install tox
script:
- tox -e $TOX_ENV
deploy:
- provider: pypi
  server: https://pypi.python.org/pypi
  on:
    branch: pypi-release
    condition: $TOX_ENV = py27
  user: cosmo-maint
  password:
    secure: "Zh4zE8RqY53WBWqIaEol0mtjlPXGzp1IGTqeoNKbxW3yUECRRPiqmtzz+8RYbpPJ8QQcSKu7vWGI7Wdfjnj/49umxaBFBJ+l2y5waijjeA4aZLzrWSla5Xvt9f2b9FfzAQo3ymKMeiEugj6RoM8KWBJ53hEB0WHhLCvTAQeRwFU="
- provider: pypi
  server: https://testpypi.python.org/pypi
  on:
    branch: pypi-test
    condition: $TOX_ENV = py27
  user: cosmo-maint
  password:
    secure: "UEUr+aJ7PxDrL4peWkrCtzFX/RISq25gYeZOh5jGUffUDeOVbboS3Fasw14cvictjVdn91dj+qmSSR+kMido+GVHfx3F4FXWilgCh2Te0+fVqBXPbkikEpGsx+vAzCUqgKE/BV6nyxP2ZQAvFIROVwX+00l5J4ztddJhTIx5Efk="
after_deploy:
- git clone https://github.com/cloudify-cosmo/travis-utils.git
- python travis-utils/validate_pypi.py -v -b $TRAVIS_BRANCH || exit 1
