distribution: Ubuntu
venv: 'Ubuntu-agent/env'
python_path: '/usr/bin/python'
base_modules:
    plugins_common: https://github.com/cloudify-cosmo/cloudify-plugins-common/archive/master.tar.gz
    rest_client: https://github.com/cloudify-cosmo/cloudify-rest-client/archive/master.tar.gz
    script_plugin: https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/master.tar.gz
    diamond_plugin: https://github.com/cloudify-cosmo/cloudify-diamond-plugin/archive/master.tar.gz
management_modules_version: master
output_tar: Ubuntu-agent.tar.gz
keep_venv: false