distribution: Ubuntu
release: trusty
venv: 'cloudify/test_venv/env'
python_path: '/usr/bin/python'
base_modules:
    plugins_common: https://github.com/cloudify-cosmo/cloudify-plugins-common/archive/3.1rc1.tar.gz
    rest_client: https://github.com/cloudify-cosmo/cloudify-rest-client/archive/3.1rc1.tar.gz
    script_plugin: https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/1.1rc1.tar.gz
    diamond_plugin: https://github.com/cloudify-cosmo/cloudify-diamond-plugin/archive/1.1rc1.tar.gz
management_modules_version: 3.1rc1
output_tar: Ubuntu-trusty-agent.tar.gz
keep_venv: false